# Makefile -- sign32
# Copyright (c) 2021-2025 Renaud Fivet

# silence unused parameter warning
WARNINGS=-pedantic -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter
CFLAGS = $(WARNINGS) -O2
LDFLAGS = -s

all: sign32
