# Makefile -- sign32
# Copyright (c) 2021 Renaud Fivet

# silence unused parameter warning
WARNINGS=-pedantic -Wall -Wextra -Wstrict-prototypes -Wno-unused-parameter
CFLAGS = $(WARNINGS) -O2

all: sign32
